version: "3.8"

services:     
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"            
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./dev/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"